# Generated by Django 5.1.3 on 2024-12-05 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='队伍名')),
                ('description', models.TextField(blank=True, verbose_name='队伍描述')),
                ('maxNum', models.IntegerField(default=1, verbose_name='最大人数')),
                ('expireTime', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('status', models.IntegerField(choices=[(0, '公开'), (1, '私有'), (2, '加密')], default=0, verbose_name='队伍状态')),
                ('password', models.CharField(blank=True, max_length=512, verbose_name='密码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
                'db_table': 'team',
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinTime', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='队伍')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户队伍关系',
                'verbose_name_plural': '用户队伍关系',
                'db_table': 'user_team',
                'unique_together': {('userId', 'teamId')},
            },
        ),
    ]
