# Generated by Django 5.1.3 on 2024-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_create_test_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-createTime'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.URLField(blank=True, default='https://gips3.baidu.com/it/u=1004796864,1363400944&fm=3039&app=3039&f=JPEG?w=1024&h=1024', max_length=1024, verbose_name='头像URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=128, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='planetCode',
            field=models.CharField(blank=True, max_length=512, verbose_name='星球编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userStatus',
            field=models.IntegerField(default=0, verbose_name='用户状态'),
        ),
    ]
